import { EducationLevel } from "./types";

export const TARGET_WORDS = [
  "sapato", "balde", "casa", "tartaruga", "pente", "livro", "chave", "colher", "avião", "árvore"
];

export const TARGET_SYNONYMS: Record<string, string[]> = {
  sapato: ["sapatos", "sapatinho", "sapatilha", "tênis", "sandália"],
  balde: ["baldes", "baldinho", "bacia"],
  casa: ["casinha", "lar", "moradia"],
  tartaruga: ["jabuti", "tartaruguinha", "cágado"],
  pente: ["pentes", "pente de cabelo", "escova"],
  livro: ["livros", "caderneta", "caderno"],
  chave: ["chaves", "chavinha"],
  colher: ["colheres", "colherzinha"],
  "avião": ["aviao", "avion", "aeroplano", "aeronave"],
  "árvore": ["arvore", "arvorezinha", "planta"],
};

export const DISTRACTOR_WORDS = [
  "caminhão", "ferro", "folha", "chaleira", "bicicleta", "banana", "navio", "porco", "casaco", "carro"
];

export const RECOGNITION_ITEMS = [
  { id: 'sapato', label: 'Sapato', isTarget: true, synonyms: TARGET_SYNONYMS['sapato'] },
  { id: 'balde', label: 'Balde', isTarget: true, synonyms: TARGET_SYNONYMS['balde'] },
  { id: 'casa', label: 'Casa', isTarget: true, synonyms: TARGET_SYNONYMS['casa'] },
  { id: 'tartaruga', label: 'Tartaruga', isTarget: true, synonyms: TARGET_SYNONYMS['tartaruga'] },
  { id: 'pente', label: 'Pente', isTarget: true, synonyms: TARGET_SYNONYMS['pente'] },
  { id: 'livro', label: 'Livro', isTarget: true, synonyms: TARGET_SYNONYMS['livro'] },
  { id: 'chave', label: 'Chave', isTarget: true, synonyms: TARGET_SYNONYMS['chave'] },
  { id: 'colher', label: 'Colher', isTarget: true, synonyms: TARGET_SYNONYMS['colher'] },
  { id: 'avião', label: 'Avião', isTarget: true, synonyms: TARGET_SYNONYMS['avião'] },
  { id: 'árvore', label: 'Árvore', isTarget: true, synonyms: TARGET_SYNONYMS['árvore'] },
  { id: 'caminhão', label: 'Caminhão', isTarget: false, synonyms: ['caminhao', 'caminhonete'] },
  { id: 'ferro', label: 'Ferro de passar', isTarget: false, synonyms: ['ferro'] },
  { id: 'folha', label: 'Folha', isTarget: false },
  { id: 'chaleira', label: 'Chaleira', isTarget: false },
  { id: 'bicicleta', label: 'Bicicleta', isTarget: false, synonyms: ['bike'] },
  { id: 'banana', label: 'Banana', isTarget: false },
  { id: 'navio', label: 'Navio', isTarget: false, synonyms: ['barco'] },
  { id: 'porco', label: 'Porco', isTarget: false, synonyms: ['porquinho'] },
  { id: 'casaco', label: 'Casaco', isTarget: false, synonyms: ['paletó', 'blazer'] },
  { id: 'carro', label: 'Carro', isTarget: false },
];

export const CUTOFF_SCORES = {
  incidentalMemory: 4,
  immediateMemory: 6,
  learning: 6,
  delayedMemory: 5,
  recognition: 7,
};

export const FLUENCY_CUTOFFS = {
  [EducationLevel.ILLITERATE]: 8,
  [EducationLevel.LOW]: 11,
  [EducationLevel.HIGH]: 12,
};

// Lista expandida de animais - 1000+ nomes populares em português brasileiro
// Inclui variações ortográficas, nomes regionais e sinônimos
export const ANIMAL_LIST = new Set([
  // ============== MAMÍFEROS DOMÉSTICOS ==============
  "cachorro", "cão", "cadela", "cachorrinho", "vira-lata", "pastor alemão", "poodle", "bulldog", "labrador", "golden", "pitbull", "rottweiler", "husky", "beagle", "pinscher", "chihuahua", "dálmata", "boxer", "doberman", "akita", "shih-tzu", "yorkshire", "maltês", "pug", "buldogue", "dogue", "cocker", "lhasa", "chow-chow", "são bernardo", "terra nova", "border collie", "collie", "galgo", "basset", "schnauzer", "fox terrier", "jack russell", "west highland",
  "gato", "gata", "gatinho", "felino", "bichano", "siamês", "persa", "angorá", "maine coon", "ragdoll", "sphynx",
  "coelho", "coelha", "coelhinho", "lebre",
  "hamster", "hamsters",
  "porquinho da índia", "porquinho-da-índia", "cobaia", "preá",
  "chinchila",
  "furão", "ferret",
  "rato", "ratinho", "camundongo", "ratazana",

  // ============== MAMÍFEROS DE FAZENDA ==============
  "vaca", "boi", "touro", "bezerro", "bezerra", "novilho", "novilha", "garrote", "vitelo", "búfalo", "búfala", "zebu",
  "cavalo", "égua", "potro", "potra", "pônei", "burro", "mula", "jumento", "jegue", "asno",
  "porco", "porca", "leitão", "leitoa", "javali", "javarina", "porco do mato", "cateto", "queixada",
  "ovelha", "carneiro", "cordeiro", "cordeira", "borrego",
  "cabra", "bode", "cabrito", "cabritinha",
  "lhama", "alpaca", "vicunha", "guanaco",

  // ============== AVES DOMÉSTICAS ==============
  "galinha", "galo", "frango", "franga", "pintinho", "pinto",
  "pato", "pata", "patinho", "marreco", "marreca",
  "ganso", "gansa",
  "peru", "perua",
  "codorna", "codorniz",
  "pombo", "pomba", "pombinho", "rolinha", "rola",
  "canário", "canária",
  "periquito", "periquita",
  "papagaio", "papagaia", "louro", "loira",
  "calopsita",
  "agapornis",
  "mandarim",

  // ============== AVES SILVESTRES ==============
  "arara", "arara azul", "arara vermelha", "arara canindé", "ararinha",
  "tucano", "tucanuçu",
  "beija-flor", "beijaflor", "colibri",
  "sabiá", "sabia",
  "bem-te-vi", "bem te vi", "bemtevi",
  "pardal", "pardoca",
  "andorinha",
  "gaivota",
  "pelicano",
  "cegonha",
  "garça", "garça branca", "socó",
  "flamingo",
  "cisne",
  "pavão", "pavoa",
  "faisão", "faisoa",
  "avestruz",
  "ema",
  "casuar",
  "quivi", "kiwi",
  "pinguim", "pinguins",
  "albatroz",
  "coruja", "mocho", "caburé", "murucututu",
  "águia", "águia real", "harpia", "gavião real",
  "gavião", "gaviãozinho",
  "falcão", "falcãozinho",
  "urubu",
  "abutre",
  "condor",
  "corvo", "gralha",
  "pica-pau", "picapau",
  "martim pescador", "martim-pescador",
  "cardeal",
  "canário da terra",
  "pintassilgo",
  "curió",
  "coleiro", "coleirinho",
  "azulão",
  "sanhaço", "sanhaçu",
  "saíra",
  "tangará",
  "uirapuru",
  "galo da serra",
  "quero-quero", "quero quero", "tetéu",
  "seriema",
  "jacu",
  "mutum",
  "jacutinga",
  "araponga",
  "saguim", "sagui",
  "perdiz",
  "codorniz",
  "narceja",
  "maçarico",
  "biguá",
  "mergulhão",
  "marreca",
  "irerê",
  "colhereiro",
  "tuiuiú",
  "jaburu",
  "maguari",
  "curicaca",

  // ============== PRIMATAS ==============
  "macaco", "macaca", "macaquinho",
  "gorila",
  "chimpanzé", "chipanzé",
  "orangotango",
  "bonobo",
  "gibão",
  "babuíno", "babuino",
  "mandril",
  "lêmure", "lemure",
  "mico", "mico leão dourado", "mico-leão-dourado", "mico leão",
  "sagui", "saguim",
  "bugio", "guariba",
  "macaco prego", "macaco-prego",
  "macaco aranha", "macaco-aranha",
  "muriqui",
  "uacari",

  // ============== FELINOS SELVAGENS ==============
  "leão", "leoa", "leãozinho",
  "tigre", "tigresa",
  "leopardo", "leoparda",
  "pantera", "pantera negra",
  "onça", "onça pintada", "onça-pintada", "jaguar",
  "suçuarana", "puma", "onça parda", "onça-parda",
  "jaguatirica", "gato do mato", "gato-do-mato",
  "lince", "lince ibérico",
  "guepardo", "chita",
  "gato selvagem",
  "caracal",
  "serval",
  "jaguarundi", "gato mourisco",
  "gato maracajá",
  "gato palheiro",

  // ============== CANÍDEOS SELVAGENS ==============
  "lobo", "loba", "lobinho",
  "lobo guará", "lobo-guará",
  "raposa", "raposinha",
  "cachorro do mato", "cachorro-do-mato", "graxaim",
  "coiote",
  "chacal",
  "dingo",
  "feneco",
  "licaon",
  "hiena", "hienas",

  // ============== URSOS ==============
  "urso", "ursa", "ursinho",
  "urso polar", "urso branco",
  "urso pardo", "urso marrom",
  "urso negro",
  "panda", "panda gigante",
  "panda vermelho",
  "urso de óculos",

  // ============== ELEFANTES E GRANDES MAMÍFEROS ==============
  "elefante", "elefanta", "elefantinho",
  "elefante africano",
  "elefante asiático",
  "mamute",
  "rinoceronte", "rinocerontes",
  "hipopótamo", "hipopotamo",
  "girafa",
  "ocapi",

  // ============== CERVÍDEOS E BOVÍDEOS ==============
  "veado", "cervo", "corça", "cerva",
  "alce",
  "rena", "caribu",
  "antílope",
  "gazela",
  "gnu",
  "bisão", "bisonte", "búfalo americano",
  "iaque",
  "camurça",
  "cabra montês",
  "íbex",
  "muflão",
  "impala",
  "kudu",

  // ============== EQUÍDEOS SELVAGENS ==============
  "zebra",
  "cavalo selvagem",

  // ============== MARSUPIAIS ==============
  "canguru", "cangurus",
  "wallaby",
  "coala",
  "gambá", "saruê", "mucura",
  "cuíca",
  "wombat",
  "diabo da tasmânia",
  "opossum",
  "numbat",
  "quoll",

  // ============== ROEDORES ==============
  "esquilo", "esquilinho", "serelepe", "caxinguelê",
  "castor",
  "capivara",
  "paca",
  "cutia",
  "preá",
  "ouriço", "porco espinho", "porco-espinho",
  "marmota",
  "lemingue",
  "gerbil",
  "chinchila",
  "ratão do banhado",
  "nutria",
  "tuco-tuco",
  "mocó",

  // ============== EDENTADOS E XENARTROS ==============
  "tatu", "tatuzinho",
  "tatu bola", "tatu-bola",
  "tatu galinha",
  "tatu canastra", "tatu-canastra",
  "tamanduá", "tamandua", "tamanduá bandeira", "tamanduá mirim",
  "bicho preguiça", "bicho-preguiça", "preguiça",
  "pangolim",

  // ============== MUSTELÍDEOS E SIMILARES ==============
  "lontra", "ariranha",
  "furão",
  "doninha",
  "arminho",
  "texugo",
  "carcaju", "wolverine",
  "marta",
  "vison",
  "irara",
  "zorrilho", "cangambá",
  "quati", "quatis",
  "guaxinim", "mão pelada",
  "jupará", "kinkajou",

  // ============== CETÁCEOS ==============
  "baleia", "baleias",
  "baleia azul",
  "baleia jubarte", "jubarte",
  "baleia cachalote", "cachalote",
  "baleia orca", "orca",
  "baleia beluga", "beluga",
  "baleia franca",
  "golfinho", "golfinhos", "boto",
  "boto cor de rosa", "boto rosa",
  "toninha",
  "narval",
  "marsopa",

  // ============== PINÍPEDES ==============
  "foca", "focas",
  "leão marinho", "leão-marinho",
  "lobo marinho", "lobo-marinho",
  "morsa", "morsas",
  "elefante marinho",

  // ============== SIRÊNIOS ==============
  "peixe boi", "peixe-boi", "manati", "manatim",
  "dugongo",

  // ============== MORCEGOS ==============
  "morcego", "morcegos",

  // ============== OUTROS MAMÍFEROS ==============
  "suricato", "suricata",
  "hiena",
  "anta", "tapir",
  "javali",
  "pecari", "cateto", "queixada",
  "cervo do pantanal",
  "veado campeiro",
  "veado catingueiro",
  "mazama",

  // ============== RÉPTEIS ==============
  "cobra", "cobras", "serpente",
  "jiboia", "jibóia",
  "sucuri", "anaconda",
  "cascavel",
  "coral", "cobra coral",
  "naja",
  "píton", "piton",
  "víbora",
  "surucucu",
  "jararaca",
  "urutu",
  "caninana",
  "cobra cipó",
  "cobra d'água",
  "muçurana",
  "salamanta",
  "falsa coral",
  "cobra cega",

  "jacaré", "jacare",
  "crocodilo",
  "aligátor", "aligator",
  "gavial",
  "caimão",

  "lagarto", "lagartos",
  "lagartixa", "lagartixas",
  "iguana",
  "teiú", "tejú",
  "dragão de komodo", "dragão-de-komodo", "komodo",
  "camaleão", "camaleao",
  "calango",
  "salamandra",
  "gecko", "lagartixa",
  "lagarto monitor",
  "varano",

  "tartaruga", "tartarugas",
  "jabuti",
  "cágado",
  "tartaruga marinha",
  "tartaruga de pente",
  "tartaruga verde",
  "tracajá",

  // ============== ANFÍBIOS ==============
  "sapo", "sapos", "sapinho",
  "rã", "ras",
  "perereca", "pererecas",
  "salamandra",
  "tritão",
  "axolote",
  "cobra cega", "cecília",
  "sapo cururu",
  "sapo boi",
  "rã touro",

  // ============== PEIXES ==============
  "peixe", "peixes",
  "tubarão", "tubarões",
  "tubarão branco",
  "tubarão martelo",
  "tubarão baleia",
  "arraia", "raia",
  "piranha", "piranhas",
  "dourado",
  "tucunaré",
  "tilápia",
  "carpa",
  "pirarucu",
  "tambaqui",
  "pacu",
  "traíra",
  "lambari",
  "bagre",
  "piau",
  "mandi",
  "pintado",
  "surubim", "cachara",
  "jaú",
  "piraíba",
  "corvina",
  "robalo",
  "pescada",
  "sardinha",
  "anchova",
  "atum",
  "salmão", "salmao",
  "truta",
  "bacalhau",
  "linguado",
  "pargo",
  "garoupa",
  "mero",
  "badejo",
  "namorado",
  "cavalinha",
  "tainha",
  "peixe espada", "espadarte",
  "marlim",
  "enguia",
  "moreia",
  "peixe palhaço",
  "peixe anjo",
  "peixe cirurgião",
  "peixe borboleta",
  "peixe papagaio",
  "peixe leão",
  "baiacu", "peixe balão",
  "cavalo marinho", "cavalo-marinho",
  "peixe voador",
  "peixe lua",
  "rêmora",
  "peixe elétrico", "poraquê",
  "beta", "peixe beta",
  "guppy",
  "néon",
  "tetra",
  "paulistinha",
  "acará", "oscar",
  "kinguio", "peixe dourado",
  "cascudo",
  "coridora",
  "tamoatá",
  "mero",

  // ============== MOLUSCOS ==============
  "caramujo", "caracol",
  "lesma",
  "polvo", "polvos",
  "lula", "lulas",
  "siba", "choco",
  "ostra", "ostras",
  "mexilhão", "marisco",
  "vieira",
  "berbigão",
  "vôngole",
  "nautilo",

  // ============== CRUSTÁCEOS ==============
  "caranguejo", "caranguejos",
  "siri",
  "lagosta",
  "camarão", "camarao",
  "krill",
  "ermitão", "bernardo eremita",
  "craca",
  "tatuzinho de jardim", "tatuzinho-de-jardim", "tatu-de-jardim", "tatuzinho", "tatu bola de jardim",

  // ============== EQUINODERMOS ==============
  "estrela do mar", "estrela-do-mar",
  "ouriço do mar", "ouriço-do-mar",
  "pepino do mar", "pepino-do-mar",
  "bolacha da praia",

  // ============== CNIDÁRIOS ==============
  "água viva", "água-viva", "medusa",
  "coral", "corais",
  "anêmona", "anemona",

  // ============== INSETOS ==============
  "formiga", "formigas",
  "formiga saúva", "saúva",
  "formiga cortadeira",
  "formiga de fogo",
  "abelha", "abelhas",
  "abelha rainha",
  "zangão",
  "vespa", "vespas",
  "marimbondo",
  "mamangava", "mamangaba",
  "borboleta", "borboletas",
  "mariposa", "mariposas",
  "traça",
  "bicho da seda",
  "lagarta",
  "joaninha",
  "besouro", "besouros",
  "escaravelho",
  "rola bosta", "rola-bosta",
  "vaga lume", "vagalume", "vaga-lume", "pirilampo",
  "libélula", "libelula", "lavadeira",
  "grilo", "grilos",
  "gafanhoto", "gafanhotos",
  "esperança",
  "cigarra",
  "louva deus", "louva-deus", "louva-a-deus",
  "barata", "baratas",
  "mosca", "moscas",
  "mosquito", "mosquitos", "pernilongo", "muriçoca", "carapanã",
  "mutuca", "butuca",
  "varejeira",
  "mosca da fruta",
  "moscardo",
  "pulga", "pulgas",
  "piolho", "piolhos",
  "percevejo", "percevejos",
  "barbeiro", "chupão",
  "cupim", "cupins",
  "bicho pau", "bicho-pau",
  "bicho folha",
  "tesourinha",
  "cascudo",
  "caruncho",
  "broca",
  "mariposa",
  "traça",

  // ============== ARACNÍDEOS ==============
  "aranha", "aranhas",
  "tarântula", "tarantula", "caranguejeira",
  "aranha armadeira",
  "aranha marrom",
  "viúva negra",
  "aranha de jardim",
  "escorpião", "escorpioes",
  "carrapato", "carrapatos",
  "ácaro", "ácaros",

  // ============== MIRIÁPODES ==============
  "centopeia", "centopeias", "lacraia",
  "piolho de cobra", "gongolo", "embuá",

  // ============== VERMES ==============
  "minhoca", "minhocas",
  "sanguessuga",
  "lombriga",
  "tênia", "solitária",

  // ============== PORÍFEROS ==============
  "esponja", "esponjas",

  // ============== OUTROS INVERTEBRADOS ==============
  "planária",
  "hidra",

  // ============== VARIAÇÕES ORTOGRÁFICAS E REGIONAIS ==============
  "jacare", "jacares",
  "papagai", "papagaios",
  "urubu rei",
  "harpia",
  "sábia", "sabià",
  "andorina",
  "coelha", "coelhinha",
  "ovelhas",
  "cabrito montês",
  "veado mateiro",
  "onça preta",
  "gato do mato pequeno",
  "musaranho",
  "jupará",
  "catingueiro",
  "rapozinha",
  "mico estrela",
  "sagui de tufo branco",
  "bugio ruivo",
  "macaco barrigudo",
  "sauá",
  "guariba",
  "uivador",
  "cuxiú",
  "parauacu",
  "barrigudo",

  // ============== NOMES ALTERNATIVOS COMUNS ==============
  "passarinho", "passarinhos", "pássaro", "pássaros", "ave", "aves",
  "bicho", "bichos", "animal", "animais",
  "bichinho", "bichinhos",
  "filhote", "filhotes",
  "animal de estimação",
  "pet", "pets",
  "inseto", "insetos",
  "réptil", "reptil", "répteis",
  "anfíbio", "anfíbios",
  "mamífero", "mamíferos",
  "roedor", "roedores",
  "felino", "felinos",
  "canino", "caninos",
  "primata", "primatas",
  "cetáceo", "cetáceos",

  // ============== MAIS VARIAÇÕES E SINÔNIMOS ==============
  "porquinho", "porquinha",
  "gatinho", "gatinha",
  "cachorrinho", "cachorrinha",
  "cavalinho",
  "vaquinha",
  "boizinho",
  "carneirinho",
  "cobrinha",
  "peixinho",
  "sabiazinha",
  "urubuzu",
  "leaozinho",
  "tigrezinho",
  "ursinho", "ursinha",
  "macaquinho", "macaquinha",
  "elefantinho", "elefantinha",
  "girafa bebê", "girafinha",
  "zebrinha",
  "hipopotamozinho",
  "crocodilinho",
  "jacarezinho",
  "tartaruguinha",
  "sapinho", "sapinha",
  "pererequinha",
  "lagartinho", "lagartinha",
  "cobrazinha",
  "formiguinha",
  "abelhinha",
  "borboletinha",
  "joaninh",
  "besourinho",
  "grilinho",
  "aranhinha",
  "caramujo",
  "lesmazinha",
  "camaraozinho",
  "caranguejinho",
  "sirizinho",
  "estrelinha do mar",

  // ============== ANIMAIS MARINHOS ADICIONAIS ==============
  "caravela", "caravela portuguesa",
  "lancinha",
  "peixe lua", "mola mola",
  "peixe remo",
  "tainha",
  "enchova",
  "xaréu",
  "olho de boi",
  "bijupirá",
  "pampo",
  "pampano",
  "espada",
  "namorado",
  "cherne",
  "olhete",
  "xerelete",
  "guaiúba",
  "ariocó",
  "cação", "tubarão lixa",

  // ============== AVES ADICIONAIS ==============
  "tico-tico", "tico tico",
  "trinca-ferro", "trinca ferro",
  "pássaro preto",
  "melro",
  "chopim",
  "vira-bosta",
  "anu", "anu preto", "anu branco",
  "corruíra",
  "cambacica",
  "sebinho",
  "pitiguari",
  "saíra sete cores",
  "gaturamo",
  "ferreirinho",
  "papa capim", "papa-capim",
  "tiziu",
  "bigodinho",
  "bico de lacre",
  "diamante",
  "graúna",
  "encontro",
  "soldadinho",
  "tangarázinho",
  "tié sangue", "tiê-sangue",
  "maria preta",
  "lavadeira",
  "tesourão",
  "tesoura", "tesourinha",
  "garibaldi",
  "galo de campina",
  "cardinalzinho",
  "caboclinho",
  "patativa",
  "chorão",
  "jaçanã",
  "frango d'água", "frango d água",
  "galinhola",
  "piaçoca",
  "carão",
  "ariramba",
  "udu",
  "surucuá",
  "trogon",
  "capitão do mato",
  "anambé",
  "cotinga",
  "galo de rocha",
  "dançador",
  "cricrió",
  "inambu", "inhambú",
  "macuco",
  "juruva",
  "rapazinho",
  "joão de barro", "joao de barro",
  "casaca de couro",
  "arapaçu",
  "arapaçuzinho",
  "choca",
  "formigueiro",
  "papa formiga",
  "tovaca",
  "tapaculo",
  "gralhão",
  "cancã",
  "papa moscas",
  "guaracava",
  "verdinho",
  "maria cavaleira",
  "suiriri",
  "bentevi",
  "neinei",
  "pitangus",

  // ============== ANIMAIS EXÓTICOS ==============
  "ornitorrinco",
  "équidna",
  "tarsier",
  "lóris",
  "tenrec",
  "musaranho elefante",
  "damão", "hyrax",
  "porco formigueiro", "aardvark",
  "pangolim",
  "colugo",
  "tupaias",
  "quokka",
  "tasmanian devil",

  // ============== NOMES REGIONAIS BRASILEIROS ==============
  "quero-quero",
  "bem-te-vi",
  "joão de barro",
  "saci", "saci pererê",
  "juruva",
  "acauã",
  "carcarã", "caracará",
  "caburé",
  "corucaca",
  "inhapim",
  "juriti",
  "avoante",
  "postura",
  "picapauzinho",
  "pica pau do campo",
  "aririu",
  "piriquitinho",
  "maritaca",
  "maitaca",
  "tiriba",
  "jandaia",
  "parakeet",
  "tuim",
  "curica",
  "anacã",

  // ============== ESPÉCIES ESPECÍFICAS BRASILEIRAS ==============
  "mico leão de cara dourada",
  "mico leão preto",
  "muriqui do norte",
  "muriqui do sul",
  "onça pintada",
  "tamanduá bandeira",
  "tamanduá mirim",
  "tatu canastra",
  "tatu peba",
  "tatu de rabo mole",
  "lobo guará",
  "cachorro vinagre",
  "veado campeiro",
  "cervo do pantanal",
  "gato maracajá",
  "gato mourisco",
  "jaguarundi",
  "ariranha",
  "lontra brasileira",
  "boto cor de rosa",
  "boto cinza",
  "tucuxi",
  "toninha",
  "peixe boi amazônico",
  "peixe boi marinho",

  // ============== INVERTEBRADOS ADICIONAIS ==============
  "lambari", "piaba",
  "corimbatá", "curimbatá",
  "grumatã",
  "matrinxã",
  "piapara",
  "piracanjuba",
  "piava",
  "piraputanga",
  "jatuarana",
  "jaraqui",
  "curimatã",
  "branquinha",
  "sagüiru",
  "cascudo", "acari",
  "bodó",
  "jundiá",
  "mandubé",
  "palmito",
  "pirarara",
  "barbado",
  "dourada",
  "filhote",
  "piranambu",
  "pirabebe",
  "bicuda",

  // ============== NOMES GENÉRICOS RECONHECÍVEIS ==============
  "bicho de pé",
  "bicho geográfico",
  "bicho de coco",
  "bicho de goiaba",
]);

// Escala de Sunderland para pontuação do desenho do relógio (0-10 pontos)
export const SUNDERLAND_CRITERIA = [
  { score: 10, description: "Relógio perfeito: números bem posicionados, ponteiros corretos marcando 11:10" },
  { score: 9, description: "Pequenos erros visuais no posicionamento dos ponteiros" },
  { score: 8, description: "Erros mais significativos na posição dos ponteiros" },
  { score: 7, description: "Ponteiros completamente errados" },
  { score: 6, description: "Uso inapropriado dos ponteiros (números circulados, escrita digital)" },
  { score: 5, description: "Números em ordem inversa ou concentrados em um hemisfério" },
  { score: 4, description: "Números fora do relógio ou distorção espacial significativa" },
  { score: 3, description: "Números e relógio não conectados, ponteiros ausentes" },
  { score: 2, description: "Algum esforço para fazer a tarefa mas sem semelhança com relógio" },
  { score: 1, description: "Não compreendeu ou não tentou fazer a tarefa" },
  { score: 0, description: "Recusou ou foi incapaz de fazer qualquer tentativa" }
];
